spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: terminator@email.it
    password: secchetto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
